

import React from 'react';
import type { FolioAccountCol } from '../frontoffice/folioAccountColumns';
import type { GuestProfile } from '../../lib/frontoffice/types';
import type { PrintType } from '../../lib/print/templates';
import type {
  EventFolio,
  EventFolioEntry,
  EventInvoice,
  EventInvoiceStatus,
  EventReceipt,
  InvoiceFormSnapshot,
  ReceiptMethod,
  SimpleEventStatus,
  TableSortState,
} from './eventTypes';
import type { ManagementMainTabKey, VenueDetails, VenueFormState } from './eventShared';

export interface EventsScreen {
  DAY_IN_MS: number;
  EVENT_CHARGE_REF: string;
  PRE_EVENT_STATUS_OPTIONS: { key: SimpleEventStatus; label: string; icon?: string; }[];
  activeFolio: any;
  activeFolioBalance: number;
  activeFolioTotals: { debits: number; credits: number; };
  activePrintTab: "quote" | "invoice" | "receipt" | "xls";
  addDays: (date: Date, days: number) => Date;
  addExtraLineToDay: (dayIdx: number) => void;
  addMonths: (date: Date, months: number) => Date;
  allEvents: any[];
  balanceDue: number;
  beoCoordinatorOptions: { key: string; label: string; }[];
  beoDepartmentOptions: string[];
  beoForm: any;
  beoResponsibleOptions: string[];
  beoWorkspaceTab: string;
  buildOpeningFolioEntries: (event: any, invoice?: { id?: string; total?: number; issueDate?: string; } | null) => { id: string; date: any; description: string; debit: number; credit: number; balance: number; reference: string; }[] | { id: string; date: string; description: string; debit: number; credit: number; balance: number; reference: string | undefined; }[];
  calculateFolioTotals: (folio: EventFolio) => { debits: number; credits: number; };
  calendarDateInputValue: string;
  calendarDayNames: string[];
  calendarGridDays: { date: Date; key: string; isCurrentMonth: boolean; }[];
  calendarHeaderTitle: string;
  calendarMonthInputValue: string;
  calendarWeekDays: Date[];
  capacityOk: boolean;
  cappedPrepaymentAmount: number;
  checkInEventGroup: (event: any) => Promise<boolean>;
  clampDateToRange: (date: Date, rangeStart: Date, rangeEnd: Date) => Date;
  clashCount: number;
  clientContactName: string;
  closeEventWorkspace: () => void;
  closeFolioModal: () => void;
  closeReceiptWorkspace: () => void;
  closeVenueModal: () => void;
  computeDayAmounts: (row: { conferencePax: number; rate: number; extraLines?: Array<{ qty: number; unitPrice: number; taxGroup: string; }>; }) => { subtotal: number; };
  computeEventDurationDays: (event: any) => number;
  conferenceRate: number;
  conferenceRates: any[];
  confirmCreateInvoiceForEvent: () => void;
  confirmDocCaution: () => void;
  conflictingEvents: any[];
  createCreditNote: (folio: EventFolio) => void;
  createDebitNote: (folio: EventFolio) => void;
  customParticulars: { id: string; label: string; rate: number; }[];
  dailySchedule: { date: string; conferencePax: number; lunchPax: number; dinnerPax: number; rooms: number; rate: number; extras: Record<string, number>; extraLines: Array<{ id: string; name: string; qty: number; unitPrice: number; taxGroup: string; }>; }[];
  defaultDayRate: number;
  deleteActiveFolio: () => void;
  deleteActiveReceipt: () => void;
  deleteFolioEntry: (folio: EventFolio, entryId: string) => Promise<void>;
  detailedTaxRows: { name: string; method: string; rate: number | null; fixedAmount: number | null; effect: string; amount: number; }[];
  dinnerRate: number;
  discountEnabled: boolean;
  discountType: "percent" | "amount";
  discountValue: number;
  docCautionPrompt: { kind: "void-folio" | "unvoid-folio" | "delete-folio" | "void-receipt" | "unvoid-receipt" | "delete-receipt"; title: string; message: string; confirmLabel: string; } | null;
  editingEvent: any;
  editingEventDocSection: "accommodation" | "events";
  editingService: any;
  editingVenue: VenueDetails | null;
  endDate: string;
  eventAmountDue: (event: any) => number;
  eventCalendarDate: Date;
  eventCalendarView: "month" | "day" | "week";
  eventChargeAmount: (event: any) => number;
  eventCoordinator: string;
  eventEndsToday: (event: any) => boolean;
  eventFolios: EventFolio[];
  eventInvoices: EventInvoice[];
  eventName: string;
  eventReceipts: EventReceipt[];
  eventStaffOptions: { key: string; label: string; }[];
  eventStatus: "quote" | "confirmed" | "invoiced" | "cancelled";
  eventSubmitting: boolean;
  eventTaxExempt: boolean;
  eventTotals: { subtotal: number; tax: number; total: number; taxBreakdown: { name: string; rate: number | null; method?: string; fixedAmount?: number | null; amount: number; effect?: string; }[]; discountAmount: number; };
  expectedPax: number;
  exportEventsForView: (scope: "table" | "calendar" | "gantt", format: "pdf" | "csv") => void;
  exportFunctionSchedulePDF: () => void;
  exportFunctionSheetPDF: () => void;
  filteredFolioEntries: any;
  filteredModernVenues: VenueDetails[];
  folioAccountCols: { frameRef: React.Dispatch<React.SetStateAction<HTMLDivElement | null>>; frameStyle: React.CSSProperties; style: (key: FolioAccountCol) => { width: number; minWidth: number; maxWidth: number; }; sizer: (key: FolioAccountCol, label: string) => React.JSX.Element; };
  folioComposerOpen: boolean;
  folioCreateError: string;
  folioCreateForm: { eventId: string; openingBalance: number; note?: string; };
  folioEntryForm: { type: "charge" | "payment"; amount: number; description: string; reference?: string; costCenter?: string; revenueCenter?: string; method?: ReceiptMethod; recordedBy?: string; };
  folioEntrySearch: string;
  folioPageCount: number;
  folioPageRows: any[];
  folioSafePage: number;
  folioSortDir: "asc" | "desc";
  folioSortKey: "description" | "date" | "reference" | "charge" | "payment" | "balance" | "actions";
  followUpDate: string;
  formatCurrency: (value: number) => string;
  formatDateDisplay: (value?: string) => string;
  formatDateKey: (date: Date) => string;
  formatEventId: (id?: string) => string;
  formatFolioEntryCopy: (entry: EventFolioEntry) => { description: string; reference: string; };
  formatFolioNumber: (id?: string) => string;
  formatQuoteNumber: (eventId?: string, fallback?: string) => string;
  frontOfficeGuests: GuestProfile[];
  generateBEO: (event: any) => { eventId: any; eventName: any; organization: any; venue: any; date: any; duration: any; pax: any; residential: any; revenue: any; deposit: any; balance: any; salesManager: any; contactPerson: any; contactPhone: any; contactEmail: any; specialRequirements: any; setupTime: any; status: any; linkedQuote: any; linkedBooking: any; linkedFolio: any; roomSetup: { layout: string; tables: number; chairs: any; headTable: number; registrationTable: number; displayTable: number; } | { layout: any; tables: number; chairs: number; headTable: number; registrationTable: number; displayTable: number; }; cateringDetails: { mealType: any; teaBreaks: number; lunch: number; dinner: number; specialDietary: number; beverages: any; snacks: any; }; audioVisual: { projector: number; screen: number; soundSystem: number; microphones: number; laptop: number; internet: any; lighting: any; recording: boolean; }; staffing: { eventManager: number; waitStaff: number; kitchenStaff: number; security: number; technicalSupport: number; cleaningStaff: number; }; timeline: any; notes: any; };
  generateFunctionSheet: (event: any) => { eventId: any; eventName: any; organization: any; venue: any; date: any; duration: any; pax: any; residential: any; revenue: any; salesManager: any; contactPerson: any; contactPhone: any; contactEmail: any; specialRequirements: any; setupTime: any; roomSpecifications: { roomName: any; capacity: any; layout: any; temperature: string; lighting: string; access: string; parking: string; setupNotes: any; } | { roomName: any; capacity: number; layout: any; temperature: any; lighting: any; access: any; parking: any; setupNotes: any; }; cateringSpecifications: { serviceStyle: any; dietaryAccommodations: any; allergies: any; presentation: any; beverages: any; snacks: any; mealType: any; teaBreaks: number; lunch: number; dinner: number; specialDietary: number; }; technicalSpecifications: { backupEquipment: any; internetSpeed: any; powerRequirements: any; technicalSupport: any; notes: any; projector: number; screen: number; soundSystem: number; microphones: number; laptop: number; internet: any; lighting: any; recording: boolean; }; serviceSchedule: any; specialInstructions: any; contactList: { name: any; role: string; phone: any; email: any; }[]; };
  getConferenceInvoiceNumber: (eventsInvoiceId?: string, eventId?: string) => string;
  getConferenceReceiptNumber: (eventsReceiptId?: string, eventId?: string) => string;
  getEndOfMonth: (date: Date) => Date;
  getEventClientName: (event: any) => any;
  getEventDisplayName: (event: any) => any;
  getEventsUsingVenue: (venue: VenueDetails) => any[];
  getFolioCandidateEvents: () => any[];
  getFolioCurrentBalance: (folio: EventFolio) => number;
  getFolioEventLabel: (ev: any) => string;
  getFolioSettledStatus: (folio: EventFolio) => "Open" | "Closed";
  getInvoiceReceiptLabel: (inv: EventInvoice) => string;
  getInvoiceableProformas: () => any[];
  getNextSortState: (prev: TableSortState, column: string) => TableSortState;
  getProformaPickerLabel: (ev: any) => string;
  getProgrammeType: (event: any) => "RESIDENTIAL CONFERENCE" | "NON-RESIDENTIAL CONFERENCE" | "CONFERENCE" | "WORKSHOP" | "TRAINING" | "WEDDING" | "BANQUET" | "MEETING" | "PRODUCT LAUNCH" | "AUDITORIUM EVENT" | "EVENT";
  getStartOfMonth: (date: Date) => Date;
  getStatusColor: (status: string) => "success" | "warning" | "danger" | "primary" | "secondary" | "default";
  handleAddBeoChecklist: () => void;
  handleAddBeoInstruction: () => void;
  handleAddBeoTimeline: () => void;
  handleAddFolioEntry: () => void;
  handleCalendarDateInput: (value: string) => void;
  handleCalendarNavigate: (direction: number) => void;
  handleCalendarToday: () => void;
  handleCalendarViewChange: (view: "month" | "week" | "day") => void;
  handleContractDocx: (templateKey?: string) => void;
  handleContractPrint: (templateKey?: string) => void;
  handleCreateFolio: () => void;
  handleDeleteVenue: (venue: VenueDetails) => Promise<void>;
  handleDownloadInvoicePdf: (invoice: EventInvoice, templateOverride?: string) => void;
  handleDownloadQuotePdf: (eventData: any) => void;
  handleDownloadReceiptPdf: (receipt: EventReceipt, templateOverride?: string) => void;
  handleEditInvoiceFromFolio: (invoice?: EventInvoice | null) => void;
  handleEditReceiptFromFolio: (receipt?: EventReceipt | null) => void;
  handleEventSubmit: (statusOverride?: SimpleEventStatus) => void;
  handleExportEventXls: () => void;
  handleInvoiceDetailsSave: () => void;
  handleInvoiceSave: () => void;
  handleOpenContractFromEvent: () => void;
  handlePrintEventFolio: () => void;
  handlePrintEventInvoicePdf: (templateOverride?: string) => void;
  handlePrintQuotePdf: (templateOverride?: string) => void;
  handleReceiptSave: () => void;
  handleRemoveBeoChecklist: (index: number) => void;
  handleRemoveBeoInstruction: (index: number) => void;
  handleRemoveBeoTimeline: (index: number) => void;
  handleSaveBeoForm: () => void;
  handleSendFunctionSheetToDepartments: () => void;
  handleServiceSubmit: () => void;
  handleVenueFieldChange: (field: keyof VenueFormState, value: string) => void;
  handleVenueSubmit: () => void;
  hasWarnings: boolean;
  hiddenParticulars: { [x: string]: boolean; };
  invoiceCreateEventId: string;
  invoiceErrors: { [x: string]: string; };
  invoiceForm: { id?: string | undefined; eventId?: string | undefined; eventName?: string | undefined; clientName?: string | undefined; issueDate?: string | undefined; dueDate?: string | undefined; subtotal?: number | undefined; tax?: number | undefined; total?: number | undefined; balance?: number | undefined; status?: EventInvoiceStatus | undefined; reference?: string | undefined; notes?: string | undefined; formSnapshot?: InvoiceFormSnapshot | undefined; };
  invoiceModalMode: "create" | "edit";
  invoiceStatusMeta: { Draft: { color: "default" | "primary" | "secondary" | "success" | "warning" | "danger"; label: string; }; Issued: { color: "default" | "primary" | "secondary" | "success" | "warning" | "danger"; label: string; }; Partial: { color: "default" | "primary" | "secondary" | "success" | "warning" | "danger"; label: string; }; Paid: { color: "default" | "primary" | "secondary" | "success" | "warning" | "danger"; label: string; }; Overdue: { color: "default" | "primary" | "secondary" | "success" | "warning" | "danger"; label: string; }; };
  isAdjustMode: boolean;
  isBEOModalOpen: boolean;
  isClientEditModalOpen: boolean;
  isClientViewModalOpen: boolean;
  isContractModalOpen: boolean;
  isCreatingEvent: boolean;
  isCreatingInvoiceFromFolio: boolean;
  isEditingInvoiceDetails: boolean;
  isEventModalOpen: boolean;
  isFolioCreateModalOpen: boolean;
  isFolioModalOpen: boolean;
  isInvoiceEventPickerOpen: boolean;
  isInvoiceModalOpen: boolean;
  isReceiptModalOpen: boolean;
  isResidential: boolean;
  isServiceModalOpen: boolean;
  isVenueModalOpen: boolean;
  isViewMode: boolean;
  lastCreatedInvoiceId: string | null;
  linkedEventInvoice: EventInvoice | undefined;
  linkedEventReceipts: EventReceipt[];
  listSelectableTemplates: (type: PrintType) => { key: string; name: string; }[];
  lunchRate: number;
  managementMainTab: "active" | "events" | "completed" | "invoices" | "receipts" | "quotes" | "folios";
  cancelMissedEvent: (event: any) => Promise<boolean>;
  managementStatusFilter: string;
  markEventAsCompleted: (event: any) => Promise<boolean>;
  reopenEndedEvent: (event: any) => Promise<boolean>;
  modernVenues: VenueDetails[];
  nextAction: string;
  normalizeStatus: (status?: string) => SimpleEventStatus;
  openCreateFolioPicker: () => void;
  openCreateInvoicePicker: () => void;
  openCreateReceiptPicker: () => void;
  openEventForEdit: (event: any, adjustMode?: boolean, createInvoice?: boolean) => void;
  openEventForView: (event: any) => void;
  openEventInvoiceForm: (event: any, invoice?: EventInvoice) => void;
  openFolioDetails: (folio: EventFolio) => void;
  openInvoiceDetailEdit: (invoice: EventInvoice) => void;
  openNewEventModal: () => void;
  openReceiptFromInvoice: (invoice: EventInvoice, receipt?: EventReceipt) => void;
  openReceiptModal: (mode: "create" | "edit", receipt?: EventReceipt, eventOverride?: any) => void;
  openVenueModal: (venue?: VenueDetails | null) => void;
  orgClientEmail: string;
  orgClientId: string;
  orgContactPhone: string;
  orgName: string;
  orgSearch: string;
  padNumber: (value: number) => string;
  parseDateValue: (value?: string) => number;
  particularLabels: { conferencePax: string; lunchPax: string; dinnerPax: string; rooms: string; };
  phase1Error: string;
  prepaymentDisplay: string;
  prepaymentEnabled: boolean;
  prepaymentType: "percent" | "amount";
  prepaymentValue: number;
  printFunctionScheduleFromEvents: (events: any[], scheduleTitle: string, trackAction: string) => void;
  processRefund: (folio: EventFolio) => void;
  ratesByParticulars: boolean;
  receiptErrors: { [x: string]: string; };
  receiptForm: { id?: string | undefined; eventId?: string | undefined; eventName?: string | undefined; invoiceId?: string | undefined; clientName?: string | undefined; date?: string | undefined; amount?: number | undefined; method?: ReceiptMethod | undefined; reference?: string | undefined; checkNumber?: string | undefined; recordedBy?: string | undefined; notes?: string | undefined; status?: "Posted" | "Void" | undefined; };
  receiptInvoiceLocked: boolean;
  receiptInvoiceQuery: string;
  receiptMethodLabels: { Cash: string; Card: string; "Bank Transfer": string; "Mobile Money": string; Cheque: string; };
  receiptMethods: ReceiptMethod[];
  receiptModalMode: "create" | "edit";
  receiptPrintAfterSave: boolean;
  refreshTaxRules: () => Promise<void>;
  removeExtraLineFromDay: (dayIdx: number, lineIdx: number) => void;
  reportingEvents: any[];
  resolveCoordinatorValue: (value?: string) => string;
  resolveEventCoordinator: (event: any) => string;
  resolveEventTemplateKey: (type: PrintType) => any;
  reverseFolioEntry: (folio: EventFolio, entry: EventFolioEntry) => Promise<void>;
  roomRate: number;
  scheduleDataMap: Map<string, { conferencePax: number; lunchPax: number; dinnerPax: number; rooms: number; rate: number; extras: Record<string, number>; extraLines: { id: string; name: string; qty: number; unitPrice: number; taxGroup: string; }[]; }>;
  selectedClient: any;
  selectedContractEventInfo: any;
  selectedInvoiceTemplate: string;
  selectedProformaTemplate: string;
  selectedReceiptTemplate: string;
  setActivePrintTab: (value: React.SetStateAction<"quote" | "invoice" | "receipt" | "xls">) => void;
  setBeoWorkspaceTab: (value: React.SetStateAction<string>) => void;
  setClientContactName: (value: React.SetStateAction<string>) => void;
  setConferenceRate: (value: React.SetStateAction<number>) => void;
  setConferenceRates: (value: React.SetStateAction<any[]>) => void;
  setCustomParticulars: (value: React.SetStateAction<{ id: string; label: string; rate: number; }[]>) => void;
  setDailySchedule: (value: React.SetStateAction<{ date: string; conferencePax: number; lunchPax: number; dinnerPax: number; rooms: number; rate: number; extras: Record<string, number>; extraLines: Array<{ id: string; name: string; qty: number; unitPrice: number; taxGroup: string; }>; }[]>) => void;
  setDefaultDayRate: (value: React.SetStateAction<number>) => void;
  setDinnerRate: (value: React.SetStateAction<number>) => void;
  setDiscountEnabled: (value: React.SetStateAction<boolean>) => void;
  setDiscountType: (value: React.SetStateAction<"percent" | "amount">) => void;
  setDiscountValue: (value: React.SetStateAction<number>) => void;
  setDocCautionPrompt: (value: React.SetStateAction<{ kind: "void-folio" | "unvoid-folio" | "delete-folio" | "void-receipt" | "unvoid-receipt" | "delete-receipt"; title: string; message: string; confirmLabel: string; } | null>) => void;
  setEndDate: (value: React.SetStateAction<string>) => void;
  setEventCoordinator: (value: React.SetStateAction<string>) => void;
  setEventFolios: (value: React.SetStateAction<EventFolio[]>) => void;
  setEventName: (value: React.SetStateAction<string>) => void;
  setEventStatus: (value: React.SetStateAction<SimpleEventStatus>) => void;
  setEventTaxExempt: (value: React.SetStateAction<boolean>) => void;
  setExpectedPax: (value: React.SetStateAction<number>) => void;
  setFolioComposerOpen: (value: React.SetStateAction<boolean>) => void;
  setFolioCreateError: (value: React.SetStateAction<string>) => void;
  setFolioCreateForm: (value: React.SetStateAction<{ eventId: string; openingBalance: number; note?: string; }>) => void;
  setFolioEntryForm: (value: React.SetStateAction<{ type: "charge" | "payment"; amount: number; description: string; reference?: string; costCenter?: string; revenueCenter?: string; method?: ReceiptMethod; recordedBy?: string; }>) => void;
  setFolioEntrySearch: (value: React.SetStateAction<string>) => void;
  setFolioPage: (value: React.SetStateAction<number>) => void;
  setFollowUpDate: (value: React.SetStateAction<string>) => void;
  setHiddenParticulars: (value: React.SetStateAction<Record<string, boolean>>) => void;
  setInvoiceCreateEventId: (value: React.SetStateAction<string>) => void;
  setInvoiceForm: (value: React.SetStateAction<Partial<EventInvoice>>) => void;
  setIsBEOModalOpen: (value: React.SetStateAction<boolean>) => void;
  setIsClientEditModalOpen: (value: React.SetStateAction<boolean>) => void;
  setIsClientViewModalOpen: (value: React.SetStateAction<boolean>) => void;
  setIsContractModalOpen: (value: React.SetStateAction<boolean>) => void;
  setIsEditingInvoiceDetails: (value: React.SetStateAction<boolean>) => void;
  setIsFolioCreateModalOpen: (value: React.SetStateAction<boolean>) => void;
  setIsInvoiceEventPickerOpen: (value: React.SetStateAction<boolean>) => void;
  setIsInvoiceModalOpen: (value: React.SetStateAction<boolean>) => void;
  setIsResidential: (value: React.SetStateAction<boolean>) => void;
  setIsServiceModalOpen: (value: React.SetStateAction<boolean>) => void;
  setIsViewMode: (value: React.SetStateAction<boolean>) => void;
  setLastCreatedInvoiceId: (value: React.SetStateAction<string | null>) => void;
  setLunchRate: (value: React.SetStateAction<number>) => void;
  setManagementMainTab: (value: React.SetStateAction<ManagementMainTabKey>) => void;
  setManagementStatusFilter: (value: React.SetStateAction<string>) => void;
  setNextAction: (value: React.SetStateAction<string>) => void;
  setOrgClientEmail: (value: React.SetStateAction<string>) => void;
  setOrgClientId: (value: React.SetStateAction<string>) => void;
  setOrgContactPhone: (value: React.SetStateAction<string>) => void;
  setOrgName: (value: React.SetStateAction<string>) => void;
  setOrgSearch: (value: React.SetStateAction<string>) => void;
  setParticularLabels: (value: React.SetStateAction<{ conferencePax: string; lunchPax: string; dinnerPax: string; rooms: string; }>) => void;
  setPhase1Error: (value: React.SetStateAction<string>) => void;
  setPrepaymentEnabled: (value: React.SetStateAction<boolean>) => void;
  setPrepaymentType: (value: React.SetStateAction<"percent" | "amount">) => void;
  setPrepaymentValue: (value: React.SetStateAction<number>) => void;
  setQuoteTaxExempt: (value: React.SetStateAction<boolean>) => void;
  setRatesByParticulars: (value: React.SetStateAction<boolean>) => void;
  setReceiptErrors: (value: React.SetStateAction<Record<string, string>>) => void;
  setReceiptForm: (value: React.SetStateAction<Partial<EventReceipt>>) => void;
  setReceiptInvoiceQuery: (value: React.SetStateAction<string>) => void;
  setReceiptPrintAfterSave: (value: React.SetStateAction<boolean>) => void;
  setRoomRate: (value: React.SetStateAction<number>) => void;
  setSelectedContractEventInfo: (value: any) => void;
  setSelectedEventForBEO: (value: any) => void;
  setSelectedInvoiceTemplate: (value: React.SetStateAction<string>) => void;
  setSelectedProformaTemplate: (value: React.SetStateAction<string>) => void;
  setSelectedReceiptTemplate: (value: React.SetStateAction<string>) => void;
  setShowDiscountModal: (value: React.SetStateAction<boolean>) => void;
  setShowPrepaymentModal: (value: React.SetStateAction<boolean>) => void;
  setStartDate: (value: React.SetStateAction<string>) => void;
  setVenueKey: (value: React.SetStateAction<string>) => void;
  setVenueSearchTerm: (value: React.SetStateAction<string>) => void;
  setVenueStatusFilter: (value: React.SetStateAction<string>) => void;
  showDiscountModal: boolean;
  showPrepaymentModal: boolean;
  showQuotePrintInModal: boolean;
  sortFolioAccount: (key: FolioAccountCol) => void;
  sortRows: <T>(rows: T[], sortState: TableSortState | null, accessors: Record<string, (row: T) => any>) => T[];
  sortedFolioEntries: any[];
  startDate: string;
  toStartOfDay: (date: Date) => Date;
  todayKey: string;
  updateBeoChecklistItem: (index: number, field: string, value: any) => void;
  updateBeoFormSection: (section: "eventInfo" | "room" | "catering" | "technical", field: string, value: any) => void;
  updateBeoInstruction: (index: number, value: string) => void;
  updateBeoTimelineItem: (index: number, field: string, value: any) => void;
  updateExtraLineOnDay: (dayIdx: number, lineIdx: number, patch: Partial<{ name: string; qty: number; unitPrice: number; taxGroup: string; }>) => void;
  updateScheduleData: (date: string, updates: Partial<Map<string, { conferencePax: number; lunchPax: number; dinnerPax: number; rooms: number; rate: number; extras: Record<string, number>; extraLines: { id: string; name: string; qty: number; unitPrice: number; taxGroup: string; }[]; }> extends Map<string, infer V> ? V : never>) => void;
  venueForm: VenueFormState;
  venueKey: string;
  venueSearchTerm: string;
  venueStatusFilter: string;
  voidActiveFolio: () => void;
  unvoidActiveFolio: () => void;
  voidActiveReceipt: () => void;
  unvoidActiveReceipt: () => void;
}
