

import React from 'react';
import type { BusinessPartner } from '../../lib/accounting/models';
import type {
  GoodsIssue,
  GoodsReceiptNote,
  InvoiceItem,
  PurchaseOrder,
  PurchaseOrderItem,
  QualityCheck,
  Requisition,
  RequisitionItem,
  StockCount,
  StockCountItem,
  StockItem,
  StockTransfer,
  StockTransferItem,
  Supplier,
  SupplierInvoice,
} from '../../lib/inventory/models';
import type { ColumnSort } from '../dashboard/deskTableUi';

export interface InventoryScreen {
  STOCK_CATEGORIES: readonly ["food", "beverage", "cleaning", "maintenance", "office", "linens", "amenities", "electronics", "furniture", "other"];
  accountingSuppliers: BusinessPartner[];
  approveGRN: (grnId: string, approvedBy: string) => void;
  approveInvoice: (invoiceId: string, approvedBy: string) => void;
  availableLocations: string[];
  canActOnRequisitions: boolean;
  canDeleteInventoryDocs: boolean;
  canEditInventoryDocs: boolean;
  canEditProcessedRequisitions: boolean;
  canPrintInventoryDocs: boolean;
  canRunStockCount: boolean;
  canVoidInventoryDocs: boolean;
  cancelPurchaseOrder: (orderId: string, reason: string) => void;
  categories: ("food" | "beverage" | "cleaning" | "maintenance" | "office" | "linens" | "amenities" | "electronics" | "furniture" | "other")[];
  closeReqAction: () => void;
  computePOTax: (subtotal: number, taxTypeId: string | undefined, customRate: number) => number;
  computePOTaxLines: (subtotal: number, taxTypeId: string | undefined, customRate: number) => Array<{ name: string; amount: number; }>;
  confirmPurchaseOrder: (orderId: string, supplierId: string) => void;
  confirmReqAction: () => void;
  countCols: { frameRef: React.Dispatch<React.SetStateAction<HTMLDivElement | null>>; frameStyle: React.CSSProperties; style: (key: "number" | "status" | "lines" | "type" | "location" | "started" | "variance") => { width: number; minWidth: number; maxWidth: number; }; sizer: (key: "number" | "status" | "lines" | "type" | "location" | "started" | "variance", label: string) => React.JSX.Element; };
  countPage: number;
  countSort: { column: string; direction: "asc" | "desc"; };
  currentUserName: string;
  deletePurchaseOrder: (id: string) => void;
  departments: string[];
  editingInvoice: SupplierInvoice | null;
  editingItem: StockItem | null;
  editingPO: PurchaseOrder | null;
  editingRequisition: Requisition | null;
  editingStockCount: StockCount | null;
  editingStockTransfer: StockTransfer | null;
  editingSupplier: Supplier | null;
  filterCategory: string;
  filterLocation: string;
  filterStatus: string;
  formData: { id?: string | undefined; itemCode?: string | undefined; name?: string | undefined; description?: string | undefined; category?: "food" | "beverage" | "cleaning" | "maintenance" | "office" | "linens" | "amenities" | "electronics" | "furniture" | "other" | undefined; subcategory?: string | undefined; unit?: string | undefined; unitCost?: number | undefined; sellingPrice?: number | undefined; currentStock?: number | undefined; minimumStock?: number | undefined; maximumStock?: number | undefined; reorderPoint?: number | undefined; supplierId?: string | undefined; supplierName?: string | undefined; location?: string | undefined; binLocation?: string | undefined; expiryDate?: Date | undefined; batchNumber?: string | undefined; isActive?: boolean | undefined; isPerishable?: boolean | undefined; isSerialized?: boolean | undefined; serialNumbers?: string[] | undefined; barcode?: string | undefined; weight?: number | undefined; dimensions?: { length: number; width: number; height: number; } | undefined; notes?: string | undefined; createdAt?: Date | undefined; updatedAt?: Date | undefined; };
  generateNextInvoiceNumber: () => string;
  getCategoryColor: (category: string) => "success" | "primary" | "warning" | "secondary" | "danger" | "default";
  getFilteredIssueItems: (index: number) => StockItem[];
  getFilteredItemsForIndex: (index: number) => StockItem[];
  getFilteredPOItemsForIndex: (index: number) => StockItem[];
  getFilteredTransferItems: (index: number) => StockItem[];
  getGRN: (id: string) => GoodsReceiptNote | undefined;
  getStockStatus: (item: StockItem) => { label: string; color: string; };
  getVendorsForRequisitionLine: (line: Pick<RequisitionItem, "itemId" | "itemCode">) => Supplier[];
  goodsIssues: GoodsIssue[];
  goodsReceiptNotes: GoodsReceiptNote[];
  handleAddIssueItem: () => void;
  handleAddItem: () => void;
  handleAddPO: () => void;
  handleAddPOItem: () => void;
  handleAddRequisition: () => void;
  handleAddRequisitionItem: () => void;
  handleAddStockCount: () => void;
  handleAddStockTransfer: () => void;
  handleAddSupplier: () => void;
  handleCompleteStockCount: (count: StockCount) => Promise<void>;
  handleDeleteItem: (itemId: string) => Promise<void>;
  handleDeleteStockCount: (count: StockCount) => Promise<void>;
  handleDeleteSupplier: (supplierId: string) => Promise<void>;
  handleEditItem: (item: StockItem) => void;
  handleEditPO: (po: PurchaseOrder) => void;
  handleEditRequisition: (req: Requisition) => void;
  handleEditStockCountFromView: (count: StockCount) => void;
  handleEditSupplier: (supplier: Supplier) => void;
  handleGeneratePOPDF: () => void;
  handleGenerateRequisitionPDF: () => void;
  handleInvoicePOChange: (poId: string) => void;
  handleIssueGoods: () => void;
  handleOpenGoodsIssue: () => void;
  handleOpenGoodsReceipt: (po: PurchaseOrder) => void;
  handlePOItemChange: (itemCode: string, itemIndex: number) => void;
  handlePOSupplierChange: (supplierId: string) => void;
  handlePrintStockCount: (count: StockCount) => void;
  handleReceiveGoods: () => void;
  handleRemovePOItem: (itemId: string) => void;
  handleRemoveRequisitionItem: (itemId: string) => void;
  handleRequisitionItemChange: (itemCode: string, itemIndex: number) => void;
  handleRunThreeWayMatch: () => void;
  handleSaveInvoice: () => void;
  handleSaveItem: () => void;
  handleSavePO: () => void;
  handleSaveRequisition: () => void;
  handleSaveStockCount: () => void;
  handleSaveStockTransfer: () => void;
  handleSaveSupplier: () => void;
  handleSubmitQualityCheck: () => void;
  handleTransferStatusChange: (transfer: StockTransfer, status: StockTransfer["status"]) => void;
  handleUpdatePOItem: (itemId: string, updates: Partial<PurchaseOrderItem>) => void;
  handleUpdateRequisitionItem: (itemId: string, updates: Partial<RequisitionItem>) => void;
  handleViewItem: (item: StockItem) => void;
  handleViewPO: (po: PurchaseOrder) => void;
  handleViewRequisition: (req: Requisition) => void;
  handleViewSupplier: (supplier: Supplier) => void;
  handleVoidStockCount: (count: StockCount) => Promise<void>;
  inventoryLocations: string[];
  invoiceCols: { frameRef: React.Dispatch<React.SetStateAction<HTMLDivElement | null>>; frameStyle: React.CSSProperties; style: (key: "number" | "date" | "status" | "amount" | "po" | "grn" | "supplier" | "matching") => { width: number; minWidth: number; maxWidth: number; }; sizer: (key: "number" | "date" | "status" | "amount" | "po" | "grn" | "supplier" | "matching", label: string) => React.JSX.Element; };
  invoiceFilterStatus: string;
  invoiceFormData: Partial<SupplierInvoice> & { items?: InvoiceItem[]; };
  invoicePage: number;
  invoiceRowsPerPage: number;
  invoiceSearchTerm: string;
  invoiceSort: { column: string; direction: "asc" | "desc"; };
  isGRNViewOpen: boolean;
  isGoodsIssueOpen: boolean;
  isGoodsIssueViewOpen: boolean;
  isGoodsReceiptOpen: boolean;
  isInvoiceModalOpen: boolean;
  isInvoiceViewOpen: boolean;
  isOpen: boolean;
  isPOModalOpen: boolean;
  isPOViewOpen: boolean;
  isQualityCheckOpen: boolean;
  isRequisitionModalOpen: boolean;
  isRequisitionViewOpen: boolean;
  isStockCountOpen: boolean;
  isStockCountViewOpen: boolean;
  isStockTransferOpen: boolean;
  isStockTransferViewOpen: boolean;
  isSupplierModalOpen: boolean;
  isThreeWayMatchOpen: boolean;
  issueCols: { frameRef: React.Dispatch<React.SetStateAction<HTMLDivElement | null>>; frameStyle: React.CSSProperties; style: (key: "number" | "date" | "lines" | "department" | "issuedTo" | "value") => { width: number; minWidth: number; maxWidth: number; }; sizer: (key: "number" | "date" | "lines" | "department" | "issuedTo" | "value", label: string) => React.JSX.Element; };
  issueFormData: { department: string; issuedTo: string; items: Array<{ itemId: string; itemCode: string; itemName: string; quantity: number; unitCost: number; reason?: string; }>; notes?: string; };
  issueItemSearchTerms: { [x: number]: string; };
  issuePage: number;
  issueSearchTerm: string;
  issueSort: { column: string; direction: "asc" | "desc"; };
  itemCols: { frameRef: React.Dispatch<React.SetStateAction<HTMLDivElement | null>>; frameStyle: React.CSSProperties; style: (key: "status" | "code" | "location" | "unitCost" | "category" | "unit" | "reorder" | "item" | "onHand") => { width: number; minWidth: number; maxWidth: number; }; sizer: (key: "status" | "code" | "location" | "unitCost" | "category" | "unit" | "reorder" | "item" | "onHand", label: string) => React.JSX.Element; };
  itemSearchTerms: { [x: number]: string; };
  itemSort: { column: string; direction: "asc" | "desc"; };
  markDelivered: (orderId: string, actualDeliveryDate: Date) => void;
  markInTransit: (orderId: string) => void;
  markInvoicePaid: (invoiceId: string, paidBy: string, paymentMethod: string, paymentReference: string) => void;
  masterLocations: { id: string; code: string; name: string; isActive: boolean; department?: string | null; }[];
  matchResult: { matched: boolean; discrepancies: string[]; } | null;
  mergedSuppliers: Supplier[];
  onClose: () => void;
  onGRNViewClose: () => void;
  onGRNViewOpen: () => void;
  onGoodsIssueClose: () => void;
  onGoodsIssueViewClose: () => void;
  onGoodsIssueViewOpen: () => void;
  onGoodsReceiptClose: () => void;
  onInvoiceModalClose: () => void;
  onInvoiceModalOpen: () => void;
  onInvoiceViewClose: () => void;
  onInvoiceViewOpen: () => void;
  onPOModalClose: () => void;
  onPOViewClose: () => void;
  onQualityCheckClose: () => void;
  onRequisitionModalClose: () => void;
  onRequisitionViewClose: () => void;
  onStockCountClose: () => void;
  onStockCountViewClose: () => void;
  onStockCountViewOpen: () => void;
  onStockTransferClose: () => void;
  onStockTransferOpen: () => void;
  onStockTransferViewClose: () => void;
  onStockTransferViewOpen: () => void;
  onSupplierModalClose: () => void;
  onThreeWayMatchClose: () => void;
  onThreeWayMatchOpen: () => void;
  openQualityCheck: (grn: GoodsReceiptNote) => void;
  openReqAction: (type: "approve" | "reject" | "ready" | "convert" | "delete", req: Requisition) => void;
  pageSafe: number;
  pages: number;
  paginatedItems: StockItem[];
  paginatedPOs: PurchaseOrder[];
  paginatedRequisitions: Requisition[];
  paginatedSuppliers: Supplier[];
  poCols: { frameRef: React.Dispatch<React.SetStateAction<HTMLDivElement | null>>; frameStyle: React.CSSProperties; style: (key: "number" | "status" | "amount" | "orderDate" | "priority" | "supplier" | "expected") => { width: number; minWidth: number; maxWidth: number; }; sizer: (key: "number" | "status" | "amount" | "orderDate" | "priority" | "supplier" | "expected", label: string) => React.JSX.Element; };
  poFilterStatus: string;
  poFormData: Partial<PurchaseOrder> & { items?: PurchaseOrderItem[]; taxType?: string; taxRate?: number; };
  poItemSearchTerms: { [x: number]: string; };
  poPageSafe: number;
  poPages: number;
  poSearchTerm: string;
  poSort: { column: string; direction: "asc" | "desc"; };
  qualityCheckFormData: Partial<QualityCheck> & { items?: any[]; };
  receiptCols: { frameRef: React.Dispatch<React.SetStateAction<HTMLDivElement | null>>; frameStyle: React.CSSProperties; style: (key: "number" | "status" | "lines" | "supplier" | "expected" | "ordered") => { width: number; minWidth: number; maxWidth: number; }; sizer: (key: "number" | "status" | "lines" | "supplier" | "expected" | "ordered", label: string) => React.JSX.Element; };
  receiptItems: { itemId: string; itemCode: string; itemName: string; orderedQty: number; alreadyReceived: number; receiveNow: number; unitCost: number; batchNumber?: string; expiryDate?: Date; notes?: string; }[];
  receiptPage: number;
  receiptSort: { column: string; direction: "asc" | "desc"; };
  rejectGRN: (grnId: string, rejectedBy: string, reason: string) => void;
  rejectInvoice: (invoiceId: string, rejectedBy: string, reason: string) => void;
  reqActionModal: { type: "approve" | "reject" | "ready" | "convert" | "delete"; requisitionId: string; requisitionNumber: string; };
  reqConvertSuppliers: { [x: string]: string; };
  reqRejectReason: string;
  requisitionCols: { frameRef: React.Dispatch<React.SetStateAction<HTMLDivElement | null>>; frameStyle: React.CSSProperties; style: (key: "number" | "date" | "status" | "amount" | "items" | "requestedBy") => { width: number; minWidth: number; maxWidth: number; }; sizer: (key: "number" | "date" | "status" | "amount" | "items" | "requestedBy", label: string) => React.JSX.Element; };
  requisitionFilterStatus: string;
  requisitionFormData: Partial<Requisition> & { requestedItems?: RequisitionItem[]; };
  requisitionPageSafe: number;
  requisitionPages: number;
  requisitionSearchTerm: string;
  requisitionSort: { column: string; direction: "asc" | "desc"; };
  searchTerm: string;
  selectedGRNForQC: GoodsReceiptNote | null;
  selectedPOForReceipt: PurchaseOrder | null;
  selectedTab: string;
  sendPurchaseOrder: (orderId: string) => void;
  setCountPage: (value: React.SetStateAction<number>) => void;
  setCountSort: (value: React.SetStateAction<ColumnSort>) => void;
  setEditingInvoice: (value: React.SetStateAction<SupplierInvoice | null>) => void;
  setEditingStockTransfer: (value: React.SetStateAction<StockTransfer | null>) => void;
  setFilterCategory: (value: React.SetStateAction<string>) => void;
  setFilterLocation: (value: React.SetStateAction<string>) => void;
  setFilterStatus: (value: React.SetStateAction<string>) => void;
  setFormData: (value: React.SetStateAction<Partial<StockItem>>) => void;
  setInvoiceFilterStatus: (value: React.SetStateAction<string>) => void;
  setInvoiceFormData: (value: React.SetStateAction<Partial<SupplierInvoice> & { items?: InvoiceItem[]; }>) => void;
  setInvoicePage: (value: React.SetStateAction<number>) => void;
  setInvoiceSearchTerm: (value: React.SetStateAction<string>) => void;
  setInvoiceSort: (value: React.SetStateAction<ColumnSort>) => void;
  setIssueFormData: (value: React.SetStateAction<{ department: string; issuedTo: string; items: Array<{ itemId: string; itemCode: string; itemName: string; quantity: number; unitCost: number; reason?: string; }>; notes?: string; }>) => void;
  setIssueItemSearchTerms: (value: React.SetStateAction<Record<number, string>>) => void;
  setIssuePage: (value: React.SetStateAction<number>) => void;
  setIssueSearchTerm: (value: React.SetStateAction<string>) => void;
  setIssueSort: (value: React.SetStateAction<ColumnSort>) => void;
  setItemSearchTerms: (value: React.SetStateAction<Record<number, string>>) => void;
  setItemSort: (value: React.SetStateAction<ColumnSort>) => void;
  setMatchResult: (value: React.SetStateAction<{ matched: boolean; discrepancies: string[]; } | null>) => void;
  setPOFilterStatus: (value: React.SetStateAction<string>) => void;
  setPOFormData: (value: React.SetStateAction<Partial<PurchaseOrder> & { items?: PurchaseOrderItem[]; taxType?: string; taxRate?: number; }>) => void;
  setPOItemSearchTerms: (value: React.SetStateAction<Record<number, string>>) => void;
  setPOPage: (value: React.SetStateAction<number>) => void;
  setPOSearchTerm: (value: React.SetStateAction<string>) => void;
  setPOSort: (value: React.SetStateAction<ColumnSort>) => void;
  setPage: (value: React.SetStateAction<number>) => void;
  setQualityCheckFormData: (value: React.SetStateAction<Partial<QualityCheck> & { items?: any[]; }>) => void;
  setReceiptItems: (value: React.SetStateAction<{ itemId: string; itemCode: string; itemName: string; orderedQty: number; alreadyReceived: number; receiveNow: number; unitCost: number; batchNumber?: string; expiryDate?: Date; notes?: string; }[]>) => void;
  setReceiptPage: (value: React.SetStateAction<number>) => void;
  setReceiptSort: (value: React.SetStateAction<ColumnSort>) => void;
  setReqConvertSuppliers: (value: React.SetStateAction<Record<string, string>>) => void;
  setReqRejectReason: (value: React.SetStateAction<string>) => void;
  setRequisitionFilterStatus: (value: React.SetStateAction<string>) => void;
  setRequisitionFormData: (value: React.SetStateAction<Partial<Requisition> & { requestedItems?: RequisitionItem[]; }>) => void;
  setRequisitionPage: (value: React.SetStateAction<number>) => void;
  setRequisitionSearchTerm: (value: React.SetStateAction<string>) => void;
  setRequisitionSort: (value: React.SetStateAction<ColumnSort>) => void;
  setSearchTerm: (value: React.SetStateAction<string>) => void;
  setSelectedPOForInvoice: (value: React.SetStateAction<PurchaseOrder | null>) => void;
  setStockCountFilterStatus: (value: React.SetStateAction<string>) => void;
  setStockCountFormData: (value: React.SetStateAction<Partial<StockCount> & { items?: StockCountItem[]; }>) => void;
  setStockCountSearchTerm: (value: React.SetStateAction<string>) => void;
  setStockOpSubTab: (value: React.SetStateAction<string>) => void;
  setStockTransferFilterStatus: (value: React.SetStateAction<string>) => void;
  setStockTransferFormData: (value: React.SetStateAction<Partial<StockTransfer> & { items?: StockTransferItem[]; }>) => void;
  setStockTransferSearchTerm: (value: React.SetStateAction<string>) => void;
  setSupplierFilterCategory: (value: React.SetStateAction<string>) => void;
  setSupplierFilterPaymentTerms: (value: React.SetStateAction<string>) => void;
  setSupplierFilterStatus: (value: React.SetStateAction<string>) => void;
  setSupplierFormData: (value: React.SetStateAction<Partial<Supplier>>) => void;
  setSupplierPage: (value: React.SetStateAction<number>) => void;
  setSupplierSearchTerm: (value: React.SetStateAction<string>) => void;
  setSupplierSort: (value: React.SetStateAction<ColumnSort>) => void;
  setSupplierViewOpen: (value: React.SetStateAction<boolean>) => void;
  setTransferItemSearchTerms: (value: React.SetStateAction<Record<number, string>>) => void;
  setTransferPage: (value: React.SetStateAction<number>) => void;
  setTransferSort: (value: React.SetStateAction<ColumnSort>) => void;
  setViewOpen: (value: React.SetStateAction<boolean>) => void;
  setViewingGRN: (value: React.SetStateAction<GoodsReceiptNote | null>) => void;
  setViewingGoodsIssue: (value: React.SetStateAction<GoodsIssue | null>) => void;
  setViewingInvoice: (value: React.SetStateAction<SupplierInvoice | null>) => void;
  setViewingPO: (value: React.SetStateAction<PurchaseOrder | null>) => void;
  setViewingStockCount: (value: React.SetStateAction<StockCount | null>) => void;
  setViewingStockTransfer: (value: React.SetStateAction<StockTransfer | null>) => void;
  stockCountFilterStatus: string;
  stockCountFormData: Partial<StockCount> & { items?: StockCountItem[]; };
  stockCountSearchTerm: string;
  stockCounts: StockCount[];
  stockItems: StockItem[];
  stockOpSubTab: string;
  stockTransferFilterStatus: string;
  stockTransferFormData: Partial<StockTransfer> & { items?: StockTransferItem[]; };
  stockTransferSearchTerm: string;
  stockTransfers: StockTransfer[];
  supplierCategories: string[];
  supplierCols: { frameRef: React.Dispatch<React.SetStateAction<HTMLDivElement | null>>; frameStyle: React.CSSProperties; style: (key: "status" | "code" | "contact" | "address" | "supplier" | "supplies" | "terms") => { width: number; minWidth: number; maxWidth: number; }; sizer: (key: "status" | "code" | "contact" | "address" | "supplier" | "supplies" | "terms", label: string) => React.JSX.Element; };
  supplierFilterCategory: string;
  supplierFilterPaymentTerms: string;
  supplierFilterStatus: string;
  supplierFormData: { id?: string | undefined; code?: string | undefined; name?: string | undefined; contactPerson?: string | undefined; email?: string | undefined; phone?: string | undefined; address?: string | undefined; city?: string | undefined; country?: string | undefined; postalCode?: string | undefined; taxId?: string | undefined; paymentTerms?: "net30" | "net60" | "net90" | "immediate" | undefined; creditLimit?: number | undefined; currentBalance?: number | undefined; rating?: number | undefined; categories?: string[] | undefined; isActive?: boolean | undefined; contractStartDate?: Date | undefined; contractEndDate?: Date | undefined; performance?: { onTimeDelivery: number; qualityRating: number; responseTime: number; totalOrders: number; } | undefined; notes?: string | undefined; createdAt?: Date | undefined; updatedAt?: Date | undefined; };
  supplierInvoices: SupplierInvoice[];
  supplierPageSafe: number;
  supplierPages: number;
  supplierSearchTerm: string;
  supplierSort: { column: string; direction: "asc" | "desc"; };
  supplierStorePurchaseOrders: PurchaseOrder[];
  supplierStoreRequisitions: Requisition[];
  supplierViewOpen: boolean;
  taxOptions: { value: string; label: string; }[];
  transferCols: { frameRef: React.Dispatch<React.SetStateAction<HTMLDivElement | null>>; frameStyle: React.CSSProperties; style: (key: "number" | "date" | "status" | "items" | "from" | "to") => { width: number; minWidth: number; maxWidth: number; }; sizer: (key: "number" | "date" | "status" | "items" | "from" | "to", label: string) => React.JSX.Element; };
  transferItemSearchTerms: { [x: number]: string; };
  transferPage: number;
  transferSort: { column: string; direction: "asc" | "desc"; };
  updateGRN: (id: string, updates: Partial<GoodsReceiptNote>) => void;
  updateStockLevel: (itemId: string, quantity: number, operation: "add" | "remove" | "set", receivedUnitCost?: number) => void;
  updateSupplierInvoice: (id: string, updates: Partial<SupplierInvoice>) => void;
  upsertGoodsIssue: (issue: GoodsIssue) => void;
  viewOpen: boolean;
  viewingGRN: GoodsReceiptNote;
  viewingGoodsIssue: GoodsIssue;
  viewingInvoice: SupplierInvoice;
  viewingItem: StockItem;
  viewingPO: PurchaseOrder;
  viewingRequisition: Requisition;
  viewingStockCount: StockCount;
  viewingStockTransfer: StockTransfer;
  viewingSupplier: Supplier;
}
