'use client';

export interface CountryOption {
	code: string; // ISO 3166-1 alpha-2
	name: string;
}

// Curated comprehensive country list (ISO alpha-2 codes)
// Includes most UN member states and commonly used territories
export const COUNTRIES: CountryOption[] = [
	{ code: 'GH', name: 'Ghana' },
	{ code: 'NG', name: 'Nigeria' },
	{ code: 'CI', name: "Côte d'Ivoire" },
	{ code: 'SN', name: 'Senegal' },
	{ code: 'CM', name: 'Cameroon' },
	{ code: 'TG', name: 'Togo' },
	{ code: 'BF', name: 'Burkina Faso' },
	{ code: 'BJ', name: 'Benin' },
	{ code: 'ML', name: 'Mali' },
	{ code: 'GM', name: 'Gambia' },
	{ code: 'LR', name: 'Liberia' },
	{ code: 'SL', name: 'Sierra Leone' },
	{ code: 'GN', name: 'Guinea' },
	{ code: 'GW', name: 'Guinea-Bissau' },
	{ code: 'MR', name: 'Mauritania' },
	{ code: 'NE', name: 'Niger' },
	{ code: 'MA', name: 'Morocco' },
	{ code: 'DZ', name: 'Algeria' },
	{ code: 'TN', name: 'Tunisia' },
	{ code: 'EG', name: 'Egypt' },
	{ code: 'LY', name: 'Libya' },
	{ code: 'SD', name: 'Sudan' },
	{ code: 'SS', name: 'South Sudan' },
	{ code: 'ET', name: 'Ethiopia' },
	{ code: 'KE', name: 'Kenya' },
	{ code: 'UG', name: 'Uganda' },
	{ code: 'TZ', name: 'Tanzania' },
	{ code: 'RW', name: 'Rwanda' },
	{ code: 'BI', name: 'Burundi' },
	{ code: 'CD', name: 'Congo (DRC)' },
	{ code: 'CG', name: 'Congo (Republic)' },
	{ code: 'GA', name: 'Gabon' },
	{ code: 'GQ', name: 'Equatorial Guinea' },
	{ code: 'AO', name: 'Angola' },
	{ code: 'NA', name: 'Namibia' },
	{ code: 'BW', name: 'Botswana' },
	{ code: 'ZA', name: 'South Africa' },
	{ code: 'ZW', name: 'Zimbabwe' },
	{ code: 'ZM', name: 'Zambia' },
	{ code: 'MW', name: 'Malawi' },
	{ code: 'MZ', name: 'Mozambique' },
	{ code: 'SZ', name: 'Eswatini' },
	{ code: 'LS', name: 'Lesotho' },
	{ code: 'CV', name: 'Cabo Verde' },
	{ code: 'ST', name: 'São Tomé and Príncipe' },
	{ code: 'SC', name: 'Seychelles' },
	{ code: 'KM', name: 'Comoros' },
	{ code: 'MG', name: 'Madagascar' },
	{ code: 'MU', name: 'Mauritius' },
	{ code: 'US', name: 'United States' },
	{ code: 'CA', name: 'Canada' },
	{ code: 'MX', name: 'Mexico' },
	{ code: 'BR', name: 'Brazil' },
	{ code: 'AR', name: 'Argentina' },
	{ code: 'CL', name: 'Chile' },
	{ code: 'CO', name: 'Colombia' },
	{ code: 'PE', name: 'Peru' },
	{ code: 'VE', name: 'Venezuela' },
	{ code: 'UY', name: 'Uruguay' },
	{ code: 'PY', name: 'Paraguay' },
	{ code: 'BO', name: 'Bolivia' },
	{ code: 'EC', name: 'Ecuador' },
	{ code: 'GB', name: 'United Kingdom' },
	{ code: 'IE', name: 'Ireland' },
	{ code: 'FR', name: 'France' },
	{ code: 'DE', name: 'Germany' },
	{ code: 'IT', name: 'Italy' },
	{ code: 'ES', name: 'Spain' },
	{ code: 'PT', name: 'Portugal' },
	{ code: 'NL', name: 'Netherlands' },
	{ code: 'BE', name: 'Belgium' },
	{ code: 'LU', name: 'Luxembourg' },
	{ code: 'CH', name: 'Switzerland' },
	{ code: 'AT', name: 'Austria' },
	{ code: 'SE', name: 'Sweden' },
	{ code: 'NO', name: 'Norway' },
	{ code: 'DK', name: 'Denmark' },
	{ code: 'FI', name: 'Finland' },
	{ code: 'IS', name: 'Iceland' },
	{ code: 'PL', name: 'Poland' },
	{ code: 'CZ', name: 'Czechia' },
	{ code: 'SK', name: 'Slovakia' },
	{ code: 'HU', name: 'Hungary' },
	{ code: 'RO', name: 'Romania' },
	{ code: 'BG', name: 'Bulgaria' },
	{ code: 'GR', name: 'Greece' },
	{ code: 'TR', name: 'Türkiye' },
	{ code: 'RU', name: 'Russia' },
	{ code: 'UA', name: 'Ukraine' },
	{ code: 'BY', name: 'Belarus' },
	{ code: 'EE', name: 'Estonia' },
	{ code: 'LV', name: 'Latvia' },
	{ code: 'LT', name: 'Lithuania' },
	{ code: 'MD', name: 'Moldova' },
	{ code: 'BA', name: 'Bosnia and Herzegovina' },
	{ code: 'RS', name: 'Serbia' },
	{ code: 'ME', name: 'Montenegro' },
	{ code: 'MK', name: 'North Macedonia' },
	{ code: 'AL', name: 'Albania' },
	{ code: 'SI', name: 'Slovenia' },
	{ code: 'HR', name: 'Croatia' },
	{ code: 'XK', name: 'Kosovo' },
	{ code: 'CN', name: 'China' },
	{ code: 'JP', name: 'Japan' },
	{ code: 'KR', name: 'South Korea' },
	{ code: 'IN', name: 'India' },
	{ code: 'PK', name: 'Pakistan' },
	{ code: 'BD', name: 'Bangladesh' },
	{ code: 'LK', name: 'Sri Lanka' },
	{ code: 'NP', name: 'Nepal' },
	{ code: 'BT', name: 'Bhutan' },
	{ code: 'MM', name: 'Myanmar' },
	{ code: 'TH', name: 'Thailand' },
	{ code: 'VN', name: 'Vietnam' },
	{ code: 'KH', name: 'Cambodia' },
	{ code: 'LA', name: 'Laos' },
	{ code: 'MY', name: 'Malaysia' },
	{ code: 'SG', name: 'Singapore' },
	{ code: 'ID', name: 'Indonesia' },
	{ code: 'PH', name: 'Philippines' },
	{ code: 'BN', name: 'Brunei' },
	{ code: 'AU', name: 'Australia' },
	{ code: 'NZ', name: 'New Zealand' },
	{ code: 'AE', name: 'United Arab Emirates' },
	{ code: 'SA', name: 'Saudi Arabia' },
	{ code: 'QA', name: 'Qatar' },
	{ code: 'KW', name: 'Kuwait' },
	{ code: 'BH', name: 'Bahrain' },
	{ code: 'OM', name: 'Oman' },
	{ code: 'IR', name: 'Iran' },
	{ code: 'IQ', name: 'Iraq' },
	{ code: 'IL', name: 'Israel' },
	{ code: 'JO', name: 'Jordan' },
	{ code: 'LB', name: 'Lebanon' },
	{ code: 'PS', name: 'Palestine' },
	{ code: 'YE', name: 'Yemen' },
	{ code: 'SY', name: 'Syria' },
	{ code: 'AF', name: 'Afghanistan' },
	{ code: 'AZ', name: 'Azerbaijan' },
	{ code: 'AM', name: 'Armenia' },
	{ code: 'GE', name: 'Georgia' },
	{ code: 'KZ', name: 'Kazakhstan' },
	{ code: 'KG', name: 'Kyrgyzstan' },
	{ code: 'TJ', name: 'Tajikistan' },
	{ code: 'TM', name: 'Turkmenistan' },
	{ code: 'UZ', name: 'Uzbekistan' },
	{ code: 'HK', name: 'Hong Kong' },
	{ code: 'MO', name: 'Macao' },
	{ code: 'TW', name: 'Taiwan' },
	{ code: 'HK', name: 'Hong Kong' },
	{ code: 'MO', name: 'Macao' },
	{ code: 'TW', name: 'Taiwan' },
	{ code: 'CU', name: 'Cuba' },
	{ code: 'DO', name: 'Dominican Republic' },
	{ code: 'HT', name: 'Haiti' },
	{ code: 'JM', name: 'Jamaica' },
	{ code: 'TT', name: 'Trinidad and Tobago' },
	{ code: 'BB', name: 'Barbados' },
	{ code: 'BS', name: 'Bahamas' },
	{ code: 'BZ', name: 'Belize' },
	{ code: 'CR', name: 'Costa Rica' },
	{ code: 'GT', name: 'Guatemala' },
	{ code: 'HN', name: 'Honduras' },
	{ code: 'NI', name: 'Nicaragua' },
	{ code: 'PA', name: 'Panama' },
	{ code: 'SV', name: 'El Salvador' },
	{ code: 'BO', name: 'Bolivia' },
	{ code: 'GY', name: 'Guyana' },
	{ code: 'SR', name: 'Suriname' },
	{ code: 'PY', name: 'Paraguay' },
	{ code: 'UY', name: 'Uruguay' },
	{ code: 'VE', name: 'Venezuela' },
	{ code: 'UA', name: 'Ukraine' },
	{ code: 'TZ', name: 'Tanzania' },
];

export const countryCodeToNationalityAdjective = (code: string): string => {
	const map: Record<string, string> = {
		GH: 'ghanaian',
		NG: 'nigerian',
		CI: 'ivorian',
		US: 'american',
		GB: 'british',
		CA: 'canadian',
		DE: 'german',
		FR: 'french',
		IT: 'italian',
		ES: 'spanish',
		PT: 'portuguese',
		CN: 'chinese',
		JP: 'japanese',
		KR: 'korean',
		IN: 'indian',
		ZA: 'south_african',
		KE: 'kenyan',
		UG: 'ugandan',
		TZ: 'tanzanian',
	};
	return map[code] || 'other';
};


